---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clouddefensecollector.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "clouddefensecollector.name" . }}-ui
    helm.sh/chart: {{ include "clouddefensecollector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "clouddefensecollector.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "clouddefensecollector.name" . }}-ui
    helm.sh/chart: {{ include "clouddefensecollector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "clouddefensecollector.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "clouddefensecollector.name" . }}-ui
    helm.sh/chart: {{ include "clouddefensecollector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "clouddefensecollector.fullname" . }}-ui
subjects:
- kind: ServiceAccount
  name: {{ include "clouddefensecollector.fullname" . }}-ui
