{{- with .Values.certs }}
{{- if and .server.key .server.crt .ca.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clouddefense.fullname" $ }}-certs
  namespace: {{ include "clouddefense.namespace" $ }}
  labels:
    {{- include "clouddefense.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ $key := .server.key }}
  server.key: {{ $key | b64enc | quote }}
  {{ $crt := .server.crt }}
  server.crt: {{ $crt | b64enc | quote }}
  clouddefense.pem: {{ print $key $crt | b64enc | quote }}
  ca.crt: {{ .ca.crt | b64enc | quote }}
{{- end }}
{{- end }}