{{- if eq .Values.controller.kind "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "clouddefense.fullname" . }}
  namespace: {{ include "clouddefense.namespace" . }}
  labels:
    {{- include "clouddefense.labels" . | nindent 4 }}
  {{- if .Values.controller.annotations }}
  annotations:
  {{ toYaml .Values.controller.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "clouddefense.selectorLabels" . | nindent 6 }}
  template:
    {{- include "clouddefense.podTemplate" . | nindent 4 }}
  {{- with .Values.controller.daemonset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
{{- end }}