{{- if and .Values.clouddefense.grpc.enabled .Values.clouddefense.grpc.bind_address (not (hasPrefix "unix://" .Values.clouddefense.grpc.bind_address)) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "clouddefense.fullname" . }}-grpc
  namespace: {{ include "clouddefense.namespace" . }}
  labels:
    {{- include "clouddefense.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "clouddefense.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ include "grpc.port" . }}
{{- end }}