{{- with $dot := . }}
{{- range $service := $dot.Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clouddefense.fullname" $dot }}-{{ $service.name }}
  namespace: {{ include "clouddefense.namespace" $dot }}
  labels:
    {{- include "clouddefense.labels" $dot | nindent 4 }}
spec:
  {{- with $service }}
    {{- omit . "name" "selector" | toYaml | nindent 2 }}
  {{- end}}
  selector:
    {{- include "clouddefense.selectorLabels" $dot | nindent 4 }}
{{- end }}
{{- end }}