{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clouddefense.serviceAccountName" . }}
  namespace: {{ include "clouddefense.namespace" . }}
  labels:
    {{- include "clouddefense.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}