---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdefensesidekick.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.config.aws.rolearn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.config.aws.rolearn }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "cdefensesidekick.name" . }}
    helm.sh/chart: {{ include "cdefensesidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cdefensesidekick.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cdefensesidekick.name" . }}
    helm.sh/chart: {{ include "cdefensesidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - {{ template "cdefensesidekick.fullname" . }}
  verbs:
    - use
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cdefensesidekick.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cdefensesidekick.name" . }}
    helm.sh/chart: {{ include "cdefensesidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cdefensesidekick.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cdefensesidekick.fullname" . }}
{{- if .Values.config.policyreport.enabled  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cdefensesidekick.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cdefensesidekick.name" . }}
    helm.sh/chart: {{ include "cdefensesidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - "wgpolicyk8s.io"
  resources:
    - policyreports
    - clusterpolicyreports
  verbs:
    - get
    - create
    - delete
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cdefensesidekick.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cdefensesidekick.name" . }}
    helm.sh/chart: {{ include "cdefensesidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cdefensesidekick.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "cdefensesidekick.fullname" . }}
{{- end }}
