apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clouddefense.fullname" . }}
  namespace: {{ include "clouddefense.namespace" . }}
  labels:
    {{- include "clouddefense.labels" . | nindent 4 }}
data:
  clouddefense.yaml: |-
    {{- include "clouddefense.clouddefensecollectorConfig" . }}
    {{- toYaml .Values.clouddefense | nindent 4 }}
