# CI values for CloudDefense.
# The following values will bypass the installation of the kernel module
# and disable the kernel space driver.

# disable the kernel space driver
driver:
  enabled: false

# make CloudDefense run in userspace only mode
extra:
  args:
    - --userspace

# enforce /proc mounting since CloudDefense still tries to scan it
mounts:
  enforceProcMount: true
