# Default values to deploy Cdefense on GKE with gVisor.

# Affinity constraint for pods' scheduling.
# Needed to deploy Cdefense on the gVisor enabled nodes.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sandbox.gke.io/runtime
          operator: In
          values:
          - gvisor

# Tolerations to allow Cdefense to run on Kubernetes 1.6 masters.
# Adds the neccesssary tolerations to allow Cdefense pods to be scheduled on the gVisor enabled nodes.
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: sandbox.gke.io/runtime
    operator: Equal
    value: gvisor

# Disable the driver since it is not needed.
driver:
  enabled: false

# Enable gVisor and set the appropriate paths. 
gvisor:
  enabled: true
  runsc:
    path: /home/containerd/usr/local/sbin
    root: /run/containerd/runsc
    config: /run/containerd/runsc/config.toml

# Enable the containerd collector to enrich the syscall events with metadata.
collectors:
  enabled: true
  containerd:
    enabled: true
    socket: /run/containerd/containerd.sock

cdefensectl:
  artifact:
    install:
      # -- Enable the init container. We do not recommend installing plugins for security reasons since they are executable objects.
      # We install only "rulesfiles".
      enabled: true
    follow:
      # -- Enable the sidecar container. We do not support it yet for plugins. It is used only for rules feed such as k8saudit-rules rules.
      enabled: true
  config:
    artifact:
      install:
        # -- Do not resolve the depenencies for artifacts. By default is true, but for our use case we disable it.
        resolveDeps: false
        # -- List of artifacts to be installed by the cdefensectl init container.
        # We do not recommend installing (or following) plugins for security reasons since they are executable objects.
        refs: [cdefense-rules:0]
      follow:
        # -- List of artifacts to be followed by the cdefensectl sidecar container.
        # We do not recommend installing (or following) plugins for security reasons since they are executable objects.
        refs: [cdefense-rules:0]

# Set this to true to force Cdefense so output the logs as soon as they are emmitted.
tty: false
