{{- if or .Values.cdefensectl.artifact.install.enabled .Values.cdefensectl.artifact.follow.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdefense.fullname" . }}-cdefensectl
  namespace: {{ include "cdefense.namespace" . }}
  labels:
    {{- include "cdefense.labels" . | nindent 4 }}
data:
  cdefensectl.yaml: |-
    {{- toYaml .Values.cdefensectl.config | nindent 4 }}
{{- end }}
