{{- if eq .Values.controller.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdefense.fullname" . }}
  namespace: {{ include "cdefense.namespace" . }}
  labels:
    {{- include "cdefense.labels" . | nindent 4 }}
  {{- if .Values.controller.annotations }}
  annotations:
  {{ toYaml .Values.controller.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "cdefense.selectorLabels" . | nindent 6 }}
  template:
    {{- include "cdefense.podTemplate" . | nindent 4 }}
{{- end }}